/***********************************************************************/
/*                                                                     */
/*  FILE        :SeriaR.c                                              */
/*  DATE        :Tue, Jul 12, 2016                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h"
#include <machine.h>
#include "lcd_func.h"

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

unsigned char RevDt;
int set;
int Re;
int hint;

void wait(unsigned int count) 
{ unsigned int i, j;

 for(i=0; i<=count; i++){ 
	 for(j=0; j<=5000; j++){
		  ;
		}
	 }
 }

void func_sci()
{
		
 while(1){
	if(SCI3_2.SSR.BIT.RDRF == 1){
		
		RevDt = SCI3_2.RDR;
		
		if((RevDt & 0x01)==0x01 ) Re = 1;
		if((RevDt & 0x02)==0x02 ) Re = 2;
		if((RevDt & 0x03)==0x03 ) Re = 3;
		if((RevDt & 0x04)==0x04 ) Re = 4;
		
        if(set == Re){ 
			IO.PDR3.BYTE = 0xA0;
			
			 lcd_clear();
			 lcd_xy(1,1);
			 lcd_puts("OK");
		}else{
			
			 hint = set - Re;
			
	        if(hint == 1 || hint == -1){
			 lcd_clear();
			 lcd_xy(1,1);
			 lcd_puts("near");
		    }else{
		     lcd_clear();
			 lcd_xy(1,1);
			 lcd_puts("NO");
			}
		}
		                         
		SCI3_2.SSR.BIT.RDRF == 0;
		
	}else{
		SCI3_2.SSR.BIT.OER == 0;
		SCI3_2.SSR.BIT.FER == 0;
		SCI3_2.SSR.BIT.PER == 0;
	}
 }
} 

void main(void)
{
   IO.PCR2 = 0x01;
   IO.PCR3 = 0xFF;
   lcd_init();
   
   SCI3_2.SCR3.BIT.RE = 0;
   SCI3_2.SMR.BYTE = 0x00;
   SCI3_2.BRR = 64;
   
   SCI3_2.SSR.BIT.OER = 0;
   SCI3_2.SSR.BIT.FER = 0;
   SCI3_2.SSR.BIT.PER = 0;
   
   wait(2);
   
   lcd_xy(1,1);
   lcd_puts("ÎÞÀÝ¦¾ÝÀ¸");
  
   while(1){
     if(IO.PDR1.BIT.B4 == 0){
		 set = 1;
		 break;
	 }
	  
	 if(IO.PDR1.BIT.B5 == 0) {
		 set = 2;
		 break;
	 }
	 
	  if(IO.PDR1.BIT.B6 == 0){
		 set = 3;
		 break;
	 }
	  
	   if(IO.PDR1.BIT.B7 == 0){
		 set = 4;
		 break;
	 }
  };
   
   IO.PDR3.BYTE = 0x01;
   
   lcd_clear();
   lcd_xy(1,1);
   lcd_puts("¾ÝÀ¸ ¼­³Ø®³");
   
   
    SCI3_2.SCR3.BIT.RE = 1;
	SCI3_2.SCR3.BIT.RIE = 1;
   
   while(1);
   
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
