/***********************************************************************/
/*                                                                     */
/*  FILE        :CONT.c                                                */
/*  DATE        :Tue, Jul 26, 2016                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  

#include "iodefine.h"
#include "lcd_func.h"
#include <machine.h>

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

int pulse = 0;
int check = 0;

void WKP_func(void);	

void Right(void);	
void Left(void);	
void Plus(int);	

void main(void)
{

	IO.PCR5			= 0xF0;	
	IO.PUCR5.BYTE	= 0xFC;	
	IO.PMR5.BYTE	= 0x0D;	
	IEGR2.BYTE		= 0x00;	
	IWPR.BYTE		= 0x00;	

	IO.PMR1.BYTE	= 0xF0;	
	IEGR1.BYTE		= 0x70;	
	IRR1.BYTE		= 0x30;	

	TZ0.TCR.BYTE	= 0x23;	
	TZ0.POCR.BYTE	= 0xF8;	
	TZ.TPMR.BYTE	= 0x8E;	
	TZ.TOCR.BYTE	= 0x0C;	
	TZ0.GRA			= 25000;
	TZ0.GRC			= 0;
	TZ0.GRD			= 0;

	IENR1.BYTE		= 0x3F;
	lcd_init();	
	while(1)
	{
		if(pulse >= 0 && check == 1)
		{
			check = 0;
			TZ.TOER.BIT.EC0 = 1;
			TZ.TOER.BIT.ED0 = 1;
			TZ0.GRC = 0;
			TZ0.GRD = 0;
			TZ.TSTR.BIT.STR0 = 0;
		}
		
		lcd_xy(1,1);
		lcd_puts("pulse=");
		
		if(pulse > 0)
		{
			lcd_puts("-");
		}
		
		lcd_dataout(pulse < 0 ? -pulse : pulse);
		lcd_puts("   ");
		lcd_xy(1,2);
		lcd_puts("mode=");
		lcd_dataout(check);
		lcd_puts("   ");
	}
}

void WKP_func()
{

	if(IWPR.BIT.IWPF0 == 1)
	{
		if(check == 1)
		{
			pulse--;
			IWPR.BYTE = 0x00;
			return;
		}
		if(check == 2)
		{
			pulse++;
			IWPR.BYTE = 0x00;
			return;
		}
	}

	if(IWPR.BIT.IWPF2 == 1)
	{
		pulse = 0;				
		IWPR.BYTE = 0x00;				
		TZ.TOER.BIT.EC0 = 1;
		TZ.TOER.BIT.ED0 = 1;
		TZ0.GRC = 0;
		TZ0.GRD = 0;
		TZ.TSTR.BIT.STR0 = 0;		
		return;
	}

	if(IWPR.BIT.IWPF3 == 1)
	{
		pulse = 0;						
		IWPR.BYTE = 0x00;			
		TZ.TOER.BIT.EC0 = 1;
		TZ.TOER.BIT.ED0 = 1;
		TZ0.GRC = 0;
		TZ0.GRD = 0;
		TZ.TSTR.BIT.STR0 = 0;	
		return;
	}
}

void Left(void)
{
	if(IO.PDR5.BIT.B2 == 1)
	{
		check = 2;
		pulse = 0;
		TZ0.GRC = 0;
		TZ0.GRD = 15000;
		TZ.TOER.BIT.ED0 = 0;
		TZ0.TCNT = 0;
		TZ.TSTR.BIT.STR0 = 1;
	}
}

void Right(void)
{
	if(IO.PDR5.BIT.B3 == 1)
	{
		check = 2;
		pulse = 0;
		TZ0.GRC = 15000;
		TZ0.GRD = 0;
		TZ.TOER.BIT.EC0 = 0;
		TZ0.TCNT = 0;
		TZ.TSTR.BIT.STR0 = 1;
	}
}

void Plus(int n)
{
	if(n <=1)
	{
		if(IO.PDR5.BIT.B3 == 1)
		{
			check = 1;
			pulse = n;
			TZ0.GRC = 15000;
			TZ0.GRD = 0;
			TZ.TOER.BIT.EC0 = 0;
		}
	}
	if(n >= -1)
	{
		if(IO.PDR5.BIT.B2 == 1)
		{
			check = 1;
			pulse = -n;
			TZ0.GRC = 0;
			TZ0.GRD = 15000;
			TZ.TOER.BIT.ED0 = 0;
		}
	}
	TZ0.TCNT = 0;
	TZ.TSTR.BIT.STR0 = 1;
}



#ifdef __cplusplus
void abort(void)
{

}
#endif

