/***********************************************************************/
/*                                                                     */
/*  FILE        :lcd_func.c                                            */
/*  DATE        :Wed, Aug 27, 2008                                     */
/*  DESCRIPTION :LCD Display Program                                   */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Hitachi Project Generator (Ver.2.1).     */
/*                                                                     */
/***********************************************************************/
// ＜関数の概要＞ lcd_func
//・LCDインターフェースデータ長４ビットで動作可能
//・BFチェック省略


#include "lcd_func.h"


#define BOARD_BUG


void _lcd_wait(unsigned int wait_time)  // 待ち時間設定関数
{                                   //    wait_time=１で，約１ms程度のオーダー
    unsigned int    loop1;
    unsigned int    loop2;
    for( loop1 =0; loop1 < wait_time; loop1++){
        for( loop2 =0; loop2 < loop_const; loop2++);
    }
}

void lcd_pcr_init(void)
{
#ifndef BOARD_BUG
	LCD_CB_PCR.BIT.RS  = OUTPUT_BIT;               //    LCD RW  のコントロールビットを出力モードに設定
	LCD_CB_PCR.BIT.E   = OUTPUT_BIT;               //    LCD E   のコントロールビットを出力モードに設定
	LCD_CB_PCR.BIT.RW  = OUTPUT_BIT;               //    LCD RS  のコントロールビットを出力モードに設定

	LCD_DB_PCR.BIT.DATA = OUTPUT_BYTE;             //    LCD DATAのコントロールビットを出力モードに設定
#else
	LCD_CB_PCR.BYTE   = OUTPUT_BYTE;
	LCD_CB_PCR.BIT.OT = INPUT_BYTE;

	LCD_DB_PCR.BYTE     = OUTPUT_BYTE;             //    LCD DATAのコントロールビットを出力モードに設定
//	LCD_DB_PCR.BIT.OTHR = INPUT_BYTE;              //    LCD OTHRのコントロールビットを入力モードに設定
#endif
}

void lcd_write_data(unsigned char data, unsigned char rs)
{                                           // LCDコマンド／データ書き込み関数（4ビット用）
    unsigned char upper_data;               //    データコード上位4ビットの格納変数
    unsigned char lower_data;               //    データコード下位4ビットの格納変数
                                            //    
	lower_data = data;                      //    データコード下位4ビットを抽出
	upper_data = data >> 4;                 //    データコード上位4ビットを抽出
                                            //    
    _lcd_wait(1);                           //    約1msウエイト(テスト文字列の表示時間の間隔）----(lcd_test_4bit.cから変更)

	LCD_CB.BIT.RS   = rs;                       //    rs=0(LCD_CMD)，rs=1(LCD_DAT)
    LCD_CB.BIT.RW   = LCD_WRITE;                //    LCD 書き込みモード設定 (R/W=0) 
    LCD_CB.BIT.E    = 1;                        //    LCD E  --->Highレベル
    LCD_DB.BIT.DATA = upper_data;               //    データコード上位4ビットをLCDへ書き込む
    LCD_CB.BIT.E    = 0;                        //    LCD E  --->Lowレベル
    LCD_CB.BIT.E    = 1;                        //    LCD E  --->Highレベル
    LCD_DB.BIT.DATA = lower_data;               //    データコード下位4ビットをLCDへ書き込む
    LCD_CB.BIT.E    = 0;                        //    LCD E  --->Lowレベル
}

void lcd_init(void)                         // LCDをイニシャライズする関数（4ビット用）
{                                           //    起動時に1回だけ呼び出す
    lcd_pcr_init();

    LCD_CB.BIT.RS   = LCD_CMD;                  //    LCD コマンドモードに設定
    LCD_CB.BIT.RW   = LCD_WRITE;                //    LCD 書き込みモード設定 (R/W=0) 
    LCD_CB.BIT.E    = 0;                        //    LCD E  --->Lowレベル
                                              
    _lcd_wait(15);                              //    約15ms程度のウエイト
    LCD_CB.BIT.E    = 1;                        //    LCD E  --->Highレベル
    LCD_DB.BIT.DATA = LCD_INIT8B;               //    LCD ファンクションセット(データ長8ビット)
    LCD_CB.BIT.E    = 0;                        //    LCD E  --->Lowレベル
                                              
    _lcd_wait(5);                               //    約5ms程度のウエイト
    LCD_CB.BIT.E    = 1;                        //    LCD E  --->Highレベル
    LCD_DB.BIT.DATA = LCD_INIT8B;               //    LCD ファンクションセット(データ長8ビット)
    LCD_CB.BIT.E    = 0;                        //    LCD E  --->Lowレベル
                                              
    _lcd_wait(1);                               //    約1ms程度のウエイト
    LCD_CB.BIT.E    = 1;                        //    LCD E  --->Highレベル
    LCD_DB.BIT.DATA = LCD_INIT8B;               //    LCD ファンクションセット(データ長8ビット)
    LCD_CB.BIT.E    = 0;                        //    LCD E  --->Lowレベル
                                              
    _lcd_wait(1);                               //    約1ms程度のウエイト
    LCD_CB.BIT.E    = 1;                        //    LCD E  --->Highレベル
    LCD_DB.BIT.DATA = LCD_INIT4B;               //    LCD ファンクションセット(データ長4ビット)
    LCD_CB.BIT.E    = 0;                        //    LCD E  --->Lowレベル


    lcd_write_data(LCD_FCSET4B, LCD_CMD);   //    LCD ファンクションセット(データ長4ビット),
                                            //          N=1(1/16デューティ), F=0(5*8ドット)
    lcd_write_data(LCD_DISP_OFF, LCD_CMD);  //    LCD 表示オン／オフコントロールの設定
                                            //          D=0(表示オフ), C=0(カーソルなし), B=0(ブリンクなし)
    lcd_write_data(LCD_CLAR, LCD_CMD);      //    LCD 表示クリアの設定
    lcd_write_data(LCD_ENTSET, LCD_CMD);    //    LCD エントリモードの設定
                                            //          I/D=1(インクリメント), S=0(表示シフトしない）   
    lcd_write_data(LCD_DISP_NCUR, LCD_CMD); //    LCD 表示オン／オフコントロールの設定--------------------(lcd_test_4bit.cから変更)
                                            //      D=1(表示オン), C=1(カーソルなし), B=0(ブリンクなし)
}

void lcd_putc(unsigned char c)
{
	lcd_write_data(c, LCD_DAT);
}

void lcd_puts( char *str)                   // 文字列表示関数
{                                           //     (文字列をLCDに表示させる)
    while(*str) {                           //     
        lcd_write_data(*str, LCD_DAT);      //     文字を順次表示
        str++;
    }
}

void lcd_xy(unsigned char x, unsigned char y)   // LCD 表示位置を設定する関数
{                                               //     桁(x=1～16)，行(y=1,2）の範囲
        unsigned char adr;                      //     
        //adr=((x-1)+(y-1)*0x40) | 0x80;        //     アドレスの算出
        adr=((x-1)+(y-1)*0x40+0x80) | 0x80;
		lcd_write_data(adr, LCD_CMD);           //     DDRAMにアドレスデータを書き込む
}

void lcd_dataout( unsigned long data )          // 数値データをLCDに表示する関数--------------------(lcd_test_4bit.cから追加)
{                                               //
    unsigned char temp;                         //
    char strtemp[16];                           //     文字コードの格納変数を定義
    int i, k;                                   //
    i=0;                                        //
    do {                                        //
        temp = data % 10;                       //     下位の桁から数字を抽出
        strtemp[i++] = temp + '0';              //     数字を文字コードに変換
    } while (( data /= 10 ) != 0);              //     数値の桁数までループ
    i--;                                        //
    for( k=i; k>=0; k-- ) {                     //     上位の桁から順次
        lcd_write_data( strtemp[k], LCD_DAT);   //     数値文字を表示
    }                                           //
}

void lcd_puti(int data)
{
	int tmp;
	tmp = data / 10;
	if(tmp > 0)
		lcd_putc('0' + tmp);
	else
		lcd_putc(' ');
	lcd_putc('0' + (data % 10));
}

void lcd_clear()
{
	lcd_write_data( LCD_CLAR, LCD_CMD);
}


// 
void init_lcd(){ lcd_init(); }
void putc_lcd(unsigned char c){ lcd_putc(c); }
void puti_lcd(int data){ lcd_puti(data); }
void clear_lcd(){ lcd_clear(); }
void write_data_lcd(unsigned char data, unsigned char rs){ lcd_write_data(data, rs); }
